baseURL = 'https://twinkle-star.moe/'
languageCode = 'en-us'
title = 'twinkle-star.moe'
theme = 'hugo-theme-shell'

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "UNOFFICIAL site for Twinkle.STAR project!"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: or
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "Molokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "seal"
  pcName = "twinkle-star.moe"
  workDir = "website"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
    Hi I am 麻辣椒盐海豹! 
    Nice to meet you!
    This is an unofficial website for Twinkle.STAR project. 
    Still under development. See you soon!
   
    """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "five_stars"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["古堡龙姬", "https://space.bilibili.com/686201061/"],
    ["永恒娘Tiny", "https://space.bilibili.com/1377212676/"],
    ["dodo", "https://space.bilibili.com/1855519979/"],
    ["露米Lumi", "https://space.bilibili.com/2000609327/"],
    ["露娜Luna", "https://space.bilibili.com/1908273021"],
  ]




